# Optimization Configuration for Large-Scale COVID-19 TFT Training
# Optimized for 12,000+ patients

# Data Loading Optimization
data_loading:
  chunk_size: 1000  # Process 1000 patients at a time
  max_workers: 4     # Number of parallel workers
  memory_limit: 0.8  # Memory usage limit (80%)
  enable_caching: true
  cache_dir: "data/cache"

# Validation Optimization
validation:
  max_missing_percentage: 0.8  # More lenient validation
  outlier_detection: false      # Disable for speed
  parallel_validation: true
  validation_batch_size: 500

# Feature Engineering Optimization
feature_engineering:
  chunk_size: 500
  max_workers: 4
  enable_parallel_processing: true
  memory_cleanup_frequency: 100  # Cleanup every 100 patients

# TFT Formatting Optimization
tft_formatting:
  batch_size: 100
  max_workers: 4
  enable_batch_processing: true
  memory_optimization: true

# Data Loader Optimization
data_loader:
  batch_size: 64              # Larger batch size
  num_workers: 8              # More workers
  pin_memory: true
  prefetch_factor: 4          # Increase prefetch
  persistent_workers: true     # Keep workers alive
  drop_last: true             # Drop incomplete batches
  shuffle_buffer_size: 10000  # Large shuffle buffer

# Memory Management
memory:
  enable_garbage_collection: true
  gc_frequency: 100           # GC every 100 operations
  memory_monitoring: true
  max_memory_usage: 0.9       # 90% memory limit

# Performance Monitoring
monitoring:
  enable_performance_tracking: true
  log_memory_usage: true
  log_processing_time: true
  log_cpu_usage: true
  log_gpu_usage: true

# Caching Strategy
caching:
  enable_feature_caching: true
  cache_processed_features: true
  cache_timelines: true
  cache_validation_results: true
  cache_dir: "data/cache"
  cache_ttl: 3600  # 1 hour cache TTL

# Parallel Processing
parallel:
  enable_multiprocessing: true
  max_processes: 4
  enable_threading: true
  max_threads: 8
  process_pool_size: 4

# GPU Optimization (if available)
gpu:
  enable_mixed_precision: true
  enable_cudnn_benchmark: true
  enable_cudnn_deterministic: false
  memory_fraction: 0.8
  enable_gpu_monitoring: true

# Training Optimization
training:
  enable_gradient_accumulation: true
  gradient_accumulation_steps: 4
  enable_amp: true  # Automatic Mixed Precision
  enable_ddp: false  # Distributed Data Parallel
  enable_fsdp: false # Fully Sharded Data Parallel

# I/O Optimization
io:
  enable_async_loading: true
  enable_prefetching: true
  buffer_size: 10000
  enable_compression: false  # Disable for speed
  enable_serialization: true

# Error Handling
error_handling:
  enable_graceful_failures: true
  max_retries: 3
  continue_on_error: true
  log_errors: true
  save_partial_results: true 